# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d027d9d9b5cdefc3fd92e29decf4f91578c70a71f6f36e3f1168cf235e1d51569964157bf6bbe5325f8c8efe30062c996269cccb90764ec99b714b8f833f81b7

test:
  secret_key_base: ec27fcd93377927b10f9755f44954ddde0993d95ae34c08646e18e9258ca1ae38efd953b0bcb9bf261e2ce7debb7b633b3b9d0ae89f3e6bb1f0dec51e7f0d643

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
