# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default
  adapter: postgresql
  encoding: unicode
  password: packfan1
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
 <<: *default
 database: schwaddynews_development
 host: localhost

test:
 <<: *default
 database: schwaddynews_test
 host: localhost


production:
 <<: *default
 database: schwaddynews_production
 username: schwaddynews
 password: <%= ENV['SCHWADDYNEWS_DATABASE_PASSWORD'] %>
